version: '3.8'

services:
  app-service:
    image: app_service_image
    container_name: app_service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TestBd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 28762876
      SPRING_APPLICATION_NAME: TestBd

  db:
    image: postgres:latest
    container_name: app-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=TestBd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=28762876
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
